# Generated by Django 6.0.4 on 2026-04-14 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(help_text='Ex: BAT, TUR1, OWD, ACP', max_length=15)),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('documento', models.CharField(blank=True, help_text='RG, CPF ou Passaporte', max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Em metros (ex: 1.88)', max_digits=4, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Em KG (ex: 88.00)', max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(choices=[('INSTRUTOR', 'Instrutor / DM'), ('FOTOGRAFO', 'Fotógrafo'), ('STAFF', 'Staff Geral'), ('LOJA', 'Atendimento de Loja')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da operação')),
                ('horario', models.TimeField(blank=True, null=True)),
                ('embarcacao', models.CharField(default='Acqua World', max_length=100)),
                ('situacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('observacao_geral', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('neto_bat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Neto Batismo (BAT)')),
                ('neto_acp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Neto Acompanhante (ACP)')),
                ('neto_tur', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Neto Turismo (TUR)')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacote_foto', models.CharField(blank=True, help_text='Ex: F10, VIDEO, CART', max_length=50, null=True)),
                ('observacao', models.CharField(blank=True, help_text='Ex: PRECISA ROUPA COLETE E REGULADOR', max_length=255, null=True)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, help_text='Valor final vendido para este cliente', max_digits=10)),
                ('comissao_calculada', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.atividade')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.cliente')),
                ('dm_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mergulhos_guiados', to='gestao.funcionario')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiros', to='gestao.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pg', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('DEPOSITO', 'Depósito'), ('VOUCHER', 'Voucher')], max_length=20)),
                ('recebedor', models.CharField(choices=[('LOJA', 'Acqua World (Loja)'), ('VENDEDOR', 'Vendedor/Comissário')], default='LOJA', help_text='Quem está com o dinheiro/recebeu o PIX?', max_length=20)),
                ('descricao', models.CharField(blank=True, help_text='Ex: pg efferim, deposito antecipado', max_length=150, null=True)),
                ('cliente_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='gestao.clientereserva')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('descricao', models.CharField(help_text='Ex: SANGRIA ALE, LETICIA E ANDRESSA', max_length=255)),
                ('forma_pg', models.CharField(blank=True, help_text='PIX, Débito, etc.', max_length=50, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento_origem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_caixa', to='gestao.pagamento')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='gestao.vendedor'),
        ),
    ]
