# Generated by Django 6.0.4 on 2026-04-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientereserva',
            name='acerto_liquidado',
            field=models.BooleanField(default=False),
        ),
    ]
