# Generated by Django 6.0.4 on 2026-04-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_clientereserva_acerto_liquidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientereserva',
            name='data_acerto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientereserva',
            name='forma_pg_acerto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
