# Generated by Django 6.0.4 on 2026-04-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_clientereserva_data_acerto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='neto_tur',
        ),
        migrations.AddField(
            model_name='atividade',
            name='categoria_comissao',
            field=models.CharField(choices=[('BATISMO', 'Batismo'), ('ACOMPANHANTE', 'Acompanhante'), ('TURISMO_1', 'Turismo 1 Queda'), ('TURISMO_2', 'Turismo 2 Quedas'), ('SCUBA_REVIEW', 'Scuba Review'), ('CURSO', 'Curso')], default='BATISMO', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='neto_curso',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='neto_scuba',
            field=models.DecimalField(decimal_places=2, default=480.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='neto_turismo_1',
            field=models.DecimalField(decimal_places=2, default=330.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='neto_turismo_2',
            field=models.DecimalField(decimal_places=2, default=380.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='neto_acp',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='neto_bat',
            field=models.DecimalField(decimal_places=2, default=210.0, max_digits=10),
        ),
    ]
