# Generated by Django 6.0.4 on 2026-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_remove_vendedor_neto_tur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='neto_bat',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
    ]
