# Generated by Django 6.0.4 on 2026-04-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_vendedor_neto_bat'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientereserva',
            name='status_checkin',
            field=models.CharField(blank=True, choices=[('LOJA', 'Loja'), ('PIER', 'Pier')], max_length=15, null=True),
        ),
    ]
