# Generated by Django 6.0.4 on 2026-04-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_clientereserva_status_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientereserva',
            name='neto_praticado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor neto congelado no dia da venda', max_digits=10, null=True),
        ),
    ]
