# Generated by Django 6.0.4 on 2026-04-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_clientereserva_neto_praticado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientereserva',
            name='is_cortesia',
            field=models.BooleanField(default=False, verbose_name='É Cortesia?'),
        ),
        migrations.AddField(
            model_name='clientereserva',
            name='numero_pratica',
            field=models.IntegerField(default=1, verbose_name='Número da Prática'),
        ),
    ]
